admin-panel/src/main/java/ua/ivan909020/admin/domain/Order.java
package ua.ivan909020.admin.domain;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

@Entity
@Table(name = "orders")
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "orders_seq")
    @SequenceGenerator(name = "orders_seq", sequenceName = "orders_id_seq", allocationSize = 1)
    private Integer id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id", nullable = false)
    private Client client;

    @Column(name = "created_date", nullable = false)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
    private LocalDateTime createdDate;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private OrderStatus status;

    @Column(nullable = false)
    @NotNull(message = "Fill in the amount")
    @DecimalMin(value = "1.00", message = "Minimum amount is 1.00 $")
    @DecimalMax(value = "100000.00", message = "Maximum amount is 100,000.00 $")
    private Float amount;

    @Column(name = "payment_method", nullable = false)
    private String paymentMethod;

    @Column(name = "delivery_method", nullable = false)
    private String deliveryMethod;

    @Column(name = "persons_count", nullable = false)
    private Integer personsCount;

    @Column(name = "expected_delivery_time")
    private String expectedTime;

    @OneToMany(mappedBy = "order", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private List<OrderItem> items = new ArrayList<>();

    public Order() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        for (OrderItem item : items) {
            item.setOrder(this);
            this.items.add(item);
        }
    }


    public Integer getPersonsCount()
    {
        return personsCount;
    }

    public void setPersonsCount(Integer personsCount)
    {
        this.personsCount = personsCount;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    public void setDeliveryMethod(String deliveryMethod) {
        this.deliveryMethod = deliveryMethod;
    }

    public String getExpectedTime() {
        return expectedTime;
    }

    public void setExpectedTime(String expectedTime) {
        this.expectedTime = expectedTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return Objects.equals(id, order.id) &&
                Objects.equals(client, order.client) &&
                Objects.equals(createdDate, order.createdDate) &&
                status == order.status &&
                Objects.equals(amount, order.amount) &&
                Objects.equals(items, order.items);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, client, createdDate, status, amount, items, paymentMethod, deliveryMethod, expectedTime, personsCount);
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", client=" + client +
                ", createdDate=" + createdDate +
                ", status=" + status +
                ", amount=" + amount +
                ", items=" + items +
                '}';
    }

}

admin-panel/src/main/java/ua/ivan909020/admin/domain/OrderItem.java
package ua.ivan909020.admin.domain;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "order_items")
public class OrderItem {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "order_items_seq")
    @SequenceGenerator(name = "order_items_seq", sequenceName = "order_items_id_seq", allocationSize = 1)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private Product product;

    @Column(nullable = false)
    private Integer quantity;

    @Column(name = "product_name", nullable = false)
    private String productName;

    @Column(name = "product_price", nullable = false)
    private Float productPrice;

    public OrderItem() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Float getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(Float productPrice) {
        this.productPrice = productPrice;
    }

    public Float getTotalPrice() {
        return quantity * productPrice;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OrderItem orderItem = (OrderItem) o;
        return Objects.equals(id, orderItem.id) &&
                Objects.equals(order, orderItem.order) &&
                Objects.equals(product, orderItem.product) &&
                Objects.equals(quantity, orderItem.quantity) &&
                Objects.equals(productName, orderItem.productName) &&
                Objects.equals(productPrice, orderItem.productPrice);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, order, product, quantity, productName, productPrice);
    }

    @Override
    public String toString() {
        return "OrderItem{" +
                "id=" + id +
                ", order=" + order +
                ", product=" + product +
                ", quantity=" + quantity +
                ", productName='" + productName + '\'' +
                ", productPrice=" + productPrice +
                '}';
    }

}

admin-panel/src/main/java/ua/ivan909020/admin/controllers/OrderController.java
package ua.ivan909020.admin.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import ua.ivan909020.admin.domain.Order;
import ua.ivan909020.admin.services.OrderService;
import ua.ivan909020.admin.utils.ControllerUtils;
import ua.ivan909020.admin.utils.FormatDateTimeMethodModel;

import javax.validation.Valid;

@Controller
@RequestMapping("/orders")
public class OrderController {

    private final OrderService orderService;
    private final FormatDateTimeMethodModel dateTimeFormatter;

    @Autowired
    public OrderController(OrderService orderService) {
        this.orderService = orderService;
        this.dateTimeFormatter = new FormatDateTimeMethodModel();
    }

    @GetMapping
    public String showAllOrders(Model model) {
        model.addAttribute("orders", orderService.findAll());
        model.addAttribute("formatDateTime", dateTimeFormatter);
        return "orders/all";
    }

    @GetMapping("/edit/{order}")
    public String showEditOrder(Model model, @PathVariable Order order) {
        model.addAttribute("order", order);
        model.addAttribute("formatDateTime", dateTimeFormatter);
        return "orders/edit";
    }

    @PostMapping("/update")
    public String updateOrder(@Valid Order order, BindingResult bindingResult, Model model) {
        if (bindingResult.hasErrors()) {
            model.mergeAttributes(ControllerUtils.findErrors(bindingResult));
            model.addAttribute("order", order);
            model.addAttribute("formatDateTime", dateTimeFormatter);
            return "orders/edit";
        }

        orderService.update(order);
        return "redirect:/orders/edit/" + order.getId();
    }

    @PostMapping("/delete")
    public String deleteOrder(@RequestParam Integer id) {
        orderService.deleteById(id);
        return "redirect:/orders";
    }

}

admin-panel/src/main/resources/templates/orders/edit.ftlh
<#import "../macros/home.ftlh" as h>
<#import "../macros/table.ftlh" as t>

<@h.home "Детали заказа">

  <#if order??>
    <form method="post" action="orders/update">
      <div class="form-group row">
        <label class="col-sm-2">Id:</label>
        <div class="col-sm-10">
          <input class="form-control" type="number" name="id" value="${order.id?c}" readonly>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2">Клиент:</label>
        <div class="col-sm-10">
          <input type="hidden" name="client" value="${order.client.id?c}">
          ${order.client.name!} (<a target="_blank" href="clients/edit/${order.client.id?c}">view</a>)
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2">Дата:</label>
        <div class="col-sm-10">
          <input class="form-control" type="datetime-local" name="createdDate"
                 value="${formatDateTime(order.createdDate, 'yyyy-MM-dd\'T\'HH:mm')}" readonly>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2">Статус:</label>
        <div class="col-sm-10">
          <select class="form-control" name="status">
            <#list order.status.values() as status>
              <option value="${status.name()}" <#if order.status.name() == status>selected</#if>>${status.value}</option>
            </#list>
          </select>
        </div>
      </div>

      <div class="form-group row">
          <label class="col-sm-2">Способ оплаты:</label>
          <div class="col-sm-10">
              <input class="form-control" name="paymentMethod" value="${order.paymentMethod!}">
          </div>
      </div>

      <div class="form-group row">
          <label class="col-sm-2">Способ доставки:</label>
          <div class="col-sm-10">
              <input class="form-control" name="deliveryMethod" value="${order.deliveryMethod!}">
          </div>
      </div>

      <#if order.deliveryMethod = "🍽 Заказать столик">
          <div class="form-group row">
              <label class="col-sm-2">Количество персон:</label>
              <div class="col-sm-10">
                  <input class="form-control" name="personsCount" value="${order.personsCount!}">
              </div>
          </div>
      </#if>

      <div class="form-group row">
          <label class="col-sm-2">Ожидаемое время:</label>
          <div class="col-sm-10">
              <input class="form-control" name="expectedTime" value="${order.expectedTime!}">
          </div>
      </div>

      <div class="form-group row">
          <label class="col-sm-2">Итого:</label>
          <div class="col-sm-10">
              <input class="form-control" type="number" name="amount" step="any"
                       value="<#if order.amount??>${order.amount?string["0.00;; decimalSeparator='.'"]}</#if>">
              <#if amountError??><div class="text-warning">${amountError}</div></#if>
          </div>
      </div>

      <div class="mt-5">
        <h1>Элементы заказа</h1>
        <@t.table "items" />
        <table id="items" class="table table-striped table-bordered" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>Название</th>
            <th>Количество</th>
            <th>Стоимость за ед.</th>
            <th>Итоговая стоимость</th>
          </tr>
          </thead>
          <tbody>
          <#list order.items as item>
            <input type="hidden" name="items[${item?index}].id" value="${item.id?c}">
            <input type="hidden" name="items[${item?index}].order" value="${order.id?c}">
            <#if item.product??>
              <input type="hidden" name="items[${item?index}].product" value="${item.product.id?c}">
            </#if>
            <input type="hidden" name="items[${item?index}].quantity" value="${item.quantity?c}">
            <input type="hidden" name="items[${item?index}].productName" value="${item.productName}">
            <input type="hidden" name="items[${item?index}].productPrice" value="${item.productPrice?c}">
            <tr>
              <td>${item.productName}</td>
              <td>${item.quantity?c} шт.</td>
              <td>${item.productPrice} BYN</td>
              <td>${item.totalPrice} BYN</td>
            </tr>
          </#list>
          </tbody>
        </table>
      </div>

      <input type="hidden" name="_csrf" value="${_csrf.token}">
      <button class="btn btn-success" type="submit">Сохранить</button>
    </form>

    <form method="get" action="orders">
      <button class="btn btn-info" type="submit">Назад</button>
    </form>

    <form method="post" action="orders/delete">
      <input type="hidden" name="id" value="${order.id?c}">
      <input type="hidden" name="_csrf" value="${_csrf.token}">
      <button class="btn btn-danger" type="submit">Удалить</button>
    </form>

  <#else>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Error</h4>
      <hr>Этого заказа не существует!
    </div>
  </#if>

</@h.home>